name: Release

on:
  workflow_dispatch:
    inputs:
      wrapper:
        description: 'Wrapper version (1.1.0)'
        type: string
        required: true
      weasyprint:
        description: 'WeasyPrint version (63.1)'
        type: string
        required: true
      version:
        description: 'Release version (63.1.0)'
        type: string
        required: true
      publish:
        description: 'Release Type'
        required: true
        default: 'publish'
        type: choice
        options:
        - none
        - release
        - publish

jobs:
  build:
    name: Build Artifacts
    uses: ./.github/workflows/build.yaml
    with:
      wrapper: ${{ inputs.wrapper }}
      weasyprint: ${{ inputs.weasyprint }}
      version: ${{ inputs.version }}

  release:
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-22.04

    needs: build

    steps:
    
    - uses: actions/checkout@v4

    - name: Setup dotnet 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.x          

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: build-artifacts

    - name: Create release
      if: ${{ inputs.publish == 'release' || inputs.publish == 'publish' }}
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build-artifacts/*.nupkg,build-artifacts/_manifest/spdx_2.2/*.*"
        generateReleaseNotes: true
        tag: ${{ inputs.version }}

    - name: Publish to Nuget
      if: ${{ inputs.publish == 'publish' }}
      run: >
        dotnet nuget push
        build-artifacts/*.nupkg
        --source "https://api.nuget.org/v3/index.json"
        --api-key "${{ secrets.DEMACONSULTINGNUGETKEY }}"
